services:
  proxy:
    image: ${DOCKER_IMAGE:-local/network/proxy:latest}
    container_name: proxy-ingress-local-${LOGNAME}
    restart: always
    init: true
    networks:
      - dmz-ipv6
      - dmz-ipv4
    volumes:
      - proxy-logs:/var/log/squid
    cap_add:
      - ALL
      - NET_ADMIN
    cap_drop:
      - SYS_ADMIN
    ports:
      - target: 8080
        published: 8080
        protocol: tcp
    environment:
      SQUID_DAEMON_OPTS: ""
      TC_HTB_RATE: ${TC_HTB_RATE:-100Mbit}

networks:
  dmz-ipv6:
    name: dmz-${APP_NAME:-proxy}-ipv6
    driver: bridge
    enable_ipv6: true
    internal: true
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv6: "routed"
    ipam:
      driver: default
      config:
        - subnet: ${IPV6_SUBNET?Need IPV6_SUBNET}
          gateway: ${IPV6_GATEWAY?Need IPV6_GATEWAY}
  dmz-ipv4:
    name: dmz-${APP_NAME:-proxy}-ipv4
    driver: bridge
    internal: true
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: "nat"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.inhibit_ipv4: "false"
    ipam:
      driver: default
      config:
        - subnet: 10.99.5.0/24

volumes:
  proxy-logs:
    name: "logs-${APP_NAME:-proxy}"
