services:
  proxy:
    image: ${DOCKER_IMAGE:-local/network/proxy:latest}
    container_name: proxy-ingress-local-${LOGNAME}
    init: true
    restart: always
    tmpfs:
      - /tmp:size=1M
      - /var/tmp:size=1M
      - /run:size=1M
      - /var/empty:size=1M
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    mem_limit: 128m
    memswap_limit: 128m
    pids_limit: 100
    ulimits:
      nofile:
        soft: 1024
        hard: 1024
    networks:
      - dmz-ipv6
      - dmz-ipv4
    volumes:
      - proxy-logs:/var/log/squid
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      SQUID_DAEMON_OPTS: ""
      TC_HTB_RATE: ${TC_HTB_RATE:-100Mbit}

networks:
  dmz-ipv6:
    name: dmz-${APP_NAME:-proxy}-ipv6
    driver: bridge
    enable_ipv6: true
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv6: "routed"
    ipam:
      driver: default
      config:
        - subnet: "${IPV6_SUBNET}"
          gateway: "${IPV6_GATEWAY}"
  dmz-ipv4:
    name: dmz-${APP_NAME:-proxy}-ipv4
    driver: bridge
    driver_opts:
      com.docker.network.bridge.gateway_mode_ipv4: "nat"
      com.docker.network.bridge.enable_ip_masquerade: "true"
      com.docker.network.bridge.inhibit_ipv4: "false"
    ipam:
      driver: default
      config:
        - subnet: 10.99.5.0/24

volumes:
  proxy-logs:
    name: "logs-${APP_NAME:-proxy}"
